#!/usr/bin/env bash

echo "Starting script/bootstrap"

set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

cd "$DIR"
rm -rf "${DIR}/.bundle"
bundle config --local path "vendor/bundle"
if [ "$SKIP_RUBOCOP" ]; then
  without="rubocop"
else
  without=""
fi
bundle install --without="$without" --no-prune --path "vendor/bundle" --binstubs --local

echo "Completed script/bootstrap successfully"
exit 0
