#!/bin/bash

echo "Starting script/cibuild"

set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"
cd "$DIR"

# -- Bootstrap
"$DIR/script/bootstrap"

# -- Rubocop the code we care about (skip the fixture)
if [ -z "$SKIP_RUBOCOP" ]; then
  bundle exec rubocop lib/ spec/ views/
else
  echo "** Skipped rubocop tests, since \$SKIP_RUBOCOP is set."
fi

# -- rspec tests
bundle exec rspec spec/
